### ISSUE TITLE
Issue with Step 3 when Class.getResourceAsStream() is used

### ISSUE THREAD

**Issue by weiqigao** [gradle-guides/building-java-9-modules#32]
Since` Class.getResourceAsStream()` searches only in the module of the class for named modules, the run snippet

```
run {
    inputs.property("moduleName", modulename)
    doFirst {
        jvmArgs = [
            '--module-path', classpath.asPath,
            '--module', mainClassName
        ]
        classpath = files()
}
```

will cause some searches to return null.  Since the` classpath` for is presented as `build/classes/java/main:build/resources/main`, and the `module-info.class` is in `build/classes/java/main`, this causes Java to treat anything in the `build/resources/main` directory as outside the module.

The modular jar file in `build/libs` directory, on the other hand, contains both the classes and the resources files.  And therefore running the application using the modular jar will allow the `getResourceAsStream()` call to return the desired content.

Here's a simple standalone test case:
//****** build.gradle ******
```
plugins {
    id 'java'
    id 'application'
}

ext.moduleName = "modular.run"

mainClassName = "$moduleName/foo.Main"

compileJava {
    inputs.property("moduleName", moduleName)
    doFirst {
        options.compilerArgs = [
            '--module-path', classpath.asPath,
        ]
        classpath = files()
    }
}

run {
    inputs.property("moduleName", moduleName)
    doFirst {
        jvmArgs = [
            '--module-path', classpath.asPath,
            '--module', mainClassName
        ]
        classpath = files()
    }
}
```

//****** src/main/java/foo/Main.java ******
```
package foo;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.BufferedReader;

public class Main {
    public static void main(String[] args) throws Exception {
        InputStream is = Main.class.getResourceAsStream("/foo/bar.txt");
        if (is == null) {
            System.out.println("The Main.class.getResourceAsStream(\"/foo/bar.txt\") returned null.");
        } else {
            System.out.println("The Main.class.getResourceAsStream(\"/foo/bar.txt\") returned a non-null InputStream.");
            System.out.println("Its contains: " + new BufferedReader(new InputStreamReader(is)).readLine());
        }
    }
}
```

//****** src/main/java/module-info.java ******

```
module modular.run {
}
```

//****** src/main/resources/foo/bar.txt ******

```
The content of the file /foo/bar.txt.
```

And here's the different result when the application is ran two different ways:

```
$ gradle -q run
The Main.class.getResourceAsStream("/foo/bar.txt") returned null.
```

```
$ java --module-path build/libs --module modular.run/foo.Main
The Main.class.getResourceAsStream("/foo/bar.txt") returned a non-null InputStream.
Its contains: The content of the file /foo/bar.txt.
```

**Comment by b25rb2hkb25kbw** [comment]
It has been quite a long time since this was post, but I have a solution for this issue.  The answer for this question explains the cause of problem: https://stackoverflow.com/questions/53018804/how-to-access-to-resources-in-external-resource-folder-in-java-9-modular-project

Gradle creates your compiled class files into `build/classes/java/main`, and copies your resources files into `build/resources/main` (by default).  On the other hand, Java 9 Jigsaw expects that all sources of a module to be in a single directory.  As a result, Java doesn't regard the latter directory as a part of the module.  So what you want to do is just add '--patch-module', "$moduleName=${sourceSets.main.output.resourcesDir}" to your `jvmArgs` in `run` task.  Everything will work fine.

I think this information about the resources should be added to the "Building Java 9 Module" user guide...

**Comment by weiqigao** [comment]
The newly released https://github.com/java9-modularity/gradle-modules-plugin plugin solves all of these problems.  I switched to it with satisfactory results.

I'm closing this issue.
